name: train-model-job
desc: Train review prediction classification model

cmd: >
  python3 train.py ${DATA} ${MODEL}

env:
  python:
    type: manual
    version: 3.10
    requirements-file: requirements.txt

inputs:
  - data/rail-reviews.zip: DATA

outputs:
  - model.h5 : MODEL

cloud-instance-types:
  - g1.1