name: train-model-job
desc: Train review prediction classification model

cmd: >
  python3 train.py ${DATA}

env:
  python: auto

inputs:
  - data/rail-reviews.zip: DATA

outputs:
  - model.h5

cloud-instance-types:
  - g1.1